#include "RegisterDescriptors.h"

// Forward declare conversion functions
float calculatePeakV(uint16_t raw);
float calculatePeakI(uint16_t raw);

const RegisterDescriptor registers[] = {
// Friendly name														Register Name		Addr1 Addr2  #ofAddr  R/WARN		 Datatypes     Bit pos/bitlen/Conversion Conv function   Units	
 { "Meter Enable"                                                    ,           "MeterEn", {0x0 , 0x0}, 1, RW_READWRITE		, DT_BIT     , 0 , 0, 1.0f             , NULL          , "" },
 { "Current A source"                                                ,            "IA_SRC", {0x1 , 0x0}, 1, RW_READWRITE		, DT_BITFIELD, 0 , 3, 1.0f             , NULL          , "" },
 { "Current B source"                                                ,            "IB_SRC", {0x1 , 0x0}, 1, RW_READWRITE		, DT_BITFIELD, 4 , 3, 1.0f             , NULL          , "" },
 { "Current C source"                                                ,            "IC_SRC", {0x1 , 0x0}, 1, RW_READWRITE		, DT_BITFIELD, 10, 3, 1.0f             , NULL          , "" },
 { "Voltage A source"                                                ,            "UA_SRC", {0x2 , 0x0}, 1, RW_READWRITE		, DT_BITFIELD, 0 , 3, 1.0f             , NULL          , "" },
 { "Voltage B source"                                                ,            "UB_SRC", {0x2 , 0x0}, 1, RW_READWRITE		, DT_BITFIELD, 4 , 3, 1.0f             , NULL          , "" },
 { "Voltage C source"                                                ,            "UC_SRC", {0x2 , 0x0}, 1, RW_READWRITE		, DT_BITFIELD, 10, 3, 1.0f             , NULL          , "" },
 { "Voltage Sag Time"                                                ,        "Sag_Period", {0x5 , 0x0}, 1, RW_READWRITE		, DT_UINT8   , 0 , 0, 1.0f             , NULL          , "ms" },
 { "Voltage / Current Peak Time"                                     ,    "PeakDet_period", {0x5 , 0x0}, 1, RW_READWRITE		, DT_UINT8   , 8 , 0, 1.0f             , NULL          , "ms" },
 { "Over Voltage Threshold"                                          ,              "Ovth", {0x6 , 0x0}, 1, RW_READWRITE		, DT_INT16   , 0 , 0, 1.0f             , NULL          , "" },
 { "Zero Crossing Disable"                                           ,             "Zxdis", {0x7 , 0x0}, 1, RW_READWRITE		, DT_BIT     , 0 , 0, 1.0f             , NULL          , "" },
 { "Zero crossing ch 0 config"                                       ,            "ZX0Con", {0x7 , 0x0}, 1, RW_READWRITE		, DT_BITFIELD, 1 , 2, 1.0f             , NULL          , "" },
 { "Zero crossing ch 1 config"                                       ,            "ZX1Con", {0x7 , 0x0}, 1, RW_READWRITE		, DT_BITFIELD, 3 , 2, 1.0f             , NULL          , "" },
 { "Zero crossing ch 2 config"                                       ,            "ZX2Con", {0x7 , 0x0}, 1, RW_READWRITE		, DT_BITFIELD, 5 , 2, 1.0f             , NULL          , "" },
 { "Zero crossing ch 0 source"                                       ,            "ZX0Src", {0x7 , 0x0}, 1, RW_READWRITE		, DT_BITFIELD, 7 , 3, 1.0f             , NULL          , "" },
 { "Zero crossing ch 1 source"                                       ,            "ZX1Src", {0x7 , 0x0}, 1, RW_READWRITE		, DT_BITFIELD, 10, 3, 1.0f             , NULL          , "" },
 { "Zero crossing ch 2 source"                                       ,            "ZX2Src", {0x7 , 0x0}, 1, RW_READWRITE		, DT_BITFIELD, 13, 3, 1.0f             , NULL          , "" },
 { "Voltage sag threshold"                                           ,             "SagTh", {0x8 , 0x0}, 1, RW_READWRITE		, DT_INT16   , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase loss threshold"                                            ,       "PhaseLossTh", {0x9 , 0x0}, 1, RW_READWRITE		, DT_INT16   , 0 , 0, 1.0f             , NULL          , "" },
 { "Neutral Current Warning Threshold"                               ,          "InWarnTh", {0x0A, 0x0}, 1, RW_READWRITE		, DT_INT16   , 0 , 0, 1.0f             , NULL          , "" },
 { "Over Current Threshold"                                          ,              "Olth", {0x0B, 0x0}, 1, RW_READWRITE		, DT_INT16   , 0 , 0, 1.0f             , NULL          , "" },
 { "Low Frequency Threshold"                                         ,          "FreqLoTh", {0x0C, 0x0}, 1, RW_READWRITE		, DT_INT16   , 0 , 0, 0.01f            , NULL          , "Hz" },
 { "High Frequency Threshold"                                        ,          "FreqHiTh", {0x0D, 0x0}, 1, RW_READWRITE		, DT_INT16   , 0 , 0, 0.01f            , NULL          , "Hz" },
 { "Enable IRQ1 ORing with IRQ0?"                                    ,           "IRQ1_OR", {0x0F, 0x0}, 1, RW_READWRITE		, DT_BIT     , 0 , 0, 1.0f             , NULL          , "" },
 { "Enable WARN ORing with IRQ0?"                                    ,           "WARN_OR", {0x0F, 0x0}, 1, RW_READWRITE		, DT_BIT     , 1 , 0, 1.0f             , NULL          , "" },
 { "Phase A Current DC Offset"                                       ,        "IDCoffsetA", {0x14, 0x0}, 1, RW_READWRITE		, DT_INT16   , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase B Current DC Offset"                                       ,        "IDCoffsetB", {0x15, 0x0}, 1, RW_READWRITE		, DT_INT16   , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase C Current DC Offset"                                       ,        "IDCoffsetC", {0x16, 0x0}, 1, RW_READWRITE		, DT_INT16   , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase A Voltage DC Offset"                                       ,        "UDCoffsetA", {0x17, 0x0}, 1, RW_READWRITE		, DT_INT16   , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase B Voltage DC Offset"                                       ,        "UDCoffsetB", {0x18, 0x0}, 1, RW_READWRITE		, DT_INT16   , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase C Voltage DC Offset"                                       ,        "UDCoffsetC", {0x19, 0x0}, 1, RW_READWRITE		, DT_INT16   , 0 , 0, 1.0f             , NULL          , "" },
 { "Voltage gain temperature Compensation A"                         ,           "UGAINTA", {0x1A, 0x0}, 1, RW_READWRITE		, DT_UINT8   , 0 , 0, 1.0f             , NULL          , "" },
 { "Voltage gain temperature Compensation B"                         ,           "UGAINTB", {0x1A, 0x0}, 1, RW_READWRITE		, DT_UINT8   , 8 , 0, 1.0f             , NULL          , "" },
 { "Voltage gain temperature Compensation C"                         ,           "UGAINTC", {0x1B, 0x0}, 1, RW_READWRITE		, DT_UINT8   , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase compensation for frequency"                                ,              "PhiF", {0x1C, 0x0}, 1, RW_READWRITE		, DT_UINT8   , 0 , 0, 1.0f             , NULL          , "" },
 { "Current Config for Segment Compensation 0"                       ,          "LogIrms0", {0x20, 0x0}, 1, RW_READWRITE		, DT_UINT8   , 0 , 0, 1.0f             , NULL          , "" },
 { "Current Config for Segment Compensation 1"                       ,          "LogIrms1", {0x21, 0x0}, 1, RW_READWRITE		, DT_UINT8   , 0 , 0, 1.0f             , NULL          , "" },
 { "Nominal Frequency"                                               ,                "F0", {0x22, 0x0}, 1, RW_READWRITE		, DT_INT16   , 0 , 0, 0.01f            , NULL          , "Hz" },
 { "Nominal Temperature"                                             ,                "T0", {0x23, 0x0}, 1, RW_READWRITE		, DT_UINT8   , 0 , 0, 1.0f             , NULL          , "°C" },
 { "Phase A Phase Comp Segment 0"                                    ,         "PhiIrms0A", {0x24, 0x0}, 1, RW_READWRITE		, DT_UINT8   , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase A Phase Comp Segment 1"                                    ,         "PhiIrms1A", {0x24, 0x0}, 1, RW_READWRITE		, DT_UINT8   , 8 , 0, 1.0f             , NULL          , "" },
 { "Phase A Phase Comp Segment 2"                                    ,         "PhiIrms2A", {0x25, 0x0}, 1, RW_READWRITE		, DT_UINT8   , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase A Gain Comp Segment 0"                                     ,        "GainIrms0A", {0x26, 0x0}, 1, RW_READWRITE		, DT_UINT8   , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase A Gain Comp Segment 1"                                     ,        "GainIrms1A", {0x26, 0x0}, 1, RW_READWRITE		, DT_UINT8   , 8 , 0, 1.0f             , NULL          , "" },
 { "Phase A Gain Comp Segment 2"                                     ,        "GainIrms2A", {0x27, 0x0}, 1, RW_READWRITE		, DT_UINT8   , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase B Phase Comp Segment 0"                                    ,         "PhiIrms0B", {0x28, 0x0}, 1, RW_READWRITE		, DT_UINT8   , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase B Phase Comp Segment 1"                                    ,         "PhiIrms1B", {0x28, 0x0}, 1, RW_READWRITE		, DT_UINT8   , 8 , 0, 1.0f             , NULL          , "" },
 { "Phase B Phase Comp Segment 2"                                    ,         "PhiIrms2B", {0x29, 0x0}, 1, RW_READWRITE		, DT_UINT8   , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase B Gain Comp Segment 0"                                     ,        "GainIrms0B", {0x2A, 0x0}, 1, RW_READWRITE		, DT_UINT8   , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase B Gain Comp Segment 1"                                     ,        "GainIrms1B", {0x2A, 0x0}, 1, RW_READWRITE		, DT_UINT8   , 8 , 0, 1.0f             , NULL          , "" },
 { "Phase B Gain Comp Segment 2"                                     ,        "GainIrms2B", {0x2B, 0x0}, 1, RW_READWRITE		, DT_UINT8   , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase C Phase Comp Segment 0"                                    ,         "PhiIrms0C", {0x2C, 0x0}, 1, RW_READWRITE		, DT_UINT8   , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase C Phase Comp Segment 1"                                    ,         "PhiIrms1C", {0x2C, 0x0}, 1, RW_READWRITE		, DT_UINT8   , 8 , 0, 1.0f             , NULL          , "" },
 { "Phase C Phase Comp Segment 2"                                    ,         "PhiIrms2C", {0x2D, 0x0}, 1, RW_READWRITE		, DT_UINT8   , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase C Gain Comp Segment 0"                                     ,        "GainIrms0C", {0x2E, 0x0}, 1, RW_READWRITE		, DT_UINT8   , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase C Gain Comp Segment 1"                                     ,        "GainIrms1C", {0x2E, 0x0}, 1, RW_READWRITE		, DT_UINT8   , 8 , 0, 1.0f             , NULL          , "" },
 { "Phase C Gain Comp Segment 2"                                     ,        "GainIrms2C", {0x2F, 0x0}, 1, RW_READWRITE		, DT_UINT8   , 0 , 0, 1.0f             , NULL          , "" },
 { "PL Constant"                                                     ,       "PL_Constant", {0x31,0x32}, 2, RW_READWRITE		, DT_INT32   , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase C all-Phase Sum energy enable"                             ,              "EnPC", {0x33, 0x0}, 1, RW_READWRITE		, DT_BIT     , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase B all-Phase Sum energy enable"                             ,              "EnPB", {0x33, 0x0}, 1, RW_READWRITE		, DT_BIT     , 1 , 0, 1.0f             , NULL          , "" },
 { "Phase A all-Phase Sum energy enable"                             ,              "EnPA", {0x33, 0x0}, 1, RW_READWRITE		, DT_BIT     , 2 , 0, 1.0f             , NULL          , "" },
 { "Active Power summing method"                                     ,            "ABSEnP", {0x33, 0x0}, 1, RW_READWRITE		, DT_BIT     , 3 , 0, 1.0f             , NULL          , "" },
 { "Reactive Power summing method"                                   ,            "ABSEnQ", {0x33, 0x0}, 1, RW_READWRITE		, DT_BIT     , 4 , 0, 1.0f             , NULL          , "" },
 { "CF2 Pin Source"                                                  ,           "CF2varh", {0x33, 0x0}, 1, RW_READWRITE		, DT_BIT     , 7 , 0, 1.0f             , NULL          , "" },
 { "3 or 4 wire 3phase mode"                                         ,              "3P3W", {0x33, 0x0}, 1, RW_READWRITE		, DT_BIT     , 8 , 0, 1.0f             , NULL          , "" },
 { "Enable Integrator for didt current sensor"                       ,            "didtEn", {0x33, 0x0}, 1, RW_READWRITE		, DT_BIT     , 10, 0, 1.0f             , NULL          , "" },
 { "Disable HPF Signal processing"                                   ,            "HPFoff", {0x33, 0x0}, 1, RW_READWRITE		, DT_BIT     , 11, 0, 1.0f             , NULL          , "" },
 { "Grid frequency flag"                                             ,          "Freq60Hz", {0x33, 0x0}, 1, RW_READWRITE		, DT_BIT     , 12, 0, 1.0f             , NULL          , "" },
 { "PGA gain config"                                                 ,          "PGA_GAIN", {0x34, 0x0}, 1, RW_READWRITE		, DT_BITFIELD, 0 , 6, 1.0f             , NULL          , "" },
 { "Active Startup Power Threshold"                                  ,          "PStartTh", {0x35, 0x0}, 1, RW_READWRITE		, DT_UINT16  , 0 , 0, 0.00032f         , NULL          , "W" },
 { "Reactive Startup Power Threshold"                                ,          "QStartTh", {0x36, 0x0}, 1, RW_READWRITE		, DT_UINT16  , 0 , 0, 0.00032f         , NULL          , "var" },
 { "Apparent Startup Power Threshold"                                ,          "SStartTh", {0x37, 0x0}, 1, RW_READWRITE		, DT_UINT16  , 0 , 0, 0.00032f         , NULL          , "VA" },
 { "Active Startup Phase Threshold"                                  ,          "PPhaseTh", {0x38, 0x0}, 1, RW_READWRITE		, DT_UINT16  , 0 , 0, 0.00032f         , NULL          , "W/var" },
 { "Reactive Startup Phase Threshold"                                ,          "QPhaseTh", {0x39, 0x0}, 1, RW_READWRITE		, DT_UINT16  , 0 , 0, 0.00032f         , NULL          , "W/var" },
 { "Apparent Startup Phase Threshold"                                ,          "SPhaseTh", {0x3A, 0x0}, 1, RW_READWRITE		, DT_UINT16  , 0 , 0, 0.00032f         , NULL          , "W/var" },
 { "Phase A Active Power Offset"                                     ,          "PoffsetA", {0x41, 0x0}, 1, RW_READWRITE		, DT_INT16   , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase A Reactive Power Offset"                                   ,          "QoffsetA", {0x42, 0x0}, 1, RW_READWRITE		, DT_INT16   , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase B Active Power Offset"                                     ,          "PoffsetB", {0x43, 0x0}, 1, RW_READWRITE		, DT_INT16   , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase B Reactive Power Offset"                                   ,          "QoffsetB", {0x44, 0x0}, 1, RW_READWRITE		, DT_INT16   , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase C Active Power Offset"                                     ,          "PoffsetC", {0x45, 0x0}, 1, RW_READWRITE		, DT_INT16   , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase C Reactive Power Offset"                                   ,          "QoffsetC", {0x46, 0x0}, 1, RW_READWRITE		, DT_INT16   , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase A Active/reactive Energy Cal Gain"                         ,           "PQGainA", {0x47, 0x0}, 1, RW_READWRITE		, DT_INT16   , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase A Cal phase delay"                                         ,  "PhiA_DelayCycles", {0x48, 0x0}, 1, RW_READWRITE		, DT_UINT8   , 0 , 8, 0.00000048828125f, NULL          , "s" },
 { "Phase A Cal phase delay voltage"                                 ,       "PhiA_DelayV", {0x48, 0x0}, 1, RW_READWRITE		, DT_BIT     , 15, 0, 1.0f             , NULL          , "" },
 { "Phase B Active/reactive Energy Cal Gain"                         ,           "PQGainB", {0x49, 0x0}, 1, RW_READWRITE		, DT_INT16   , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase B Cal phase delay"                                         ,  "PhiB_DelayCycles", {0x4A, 0x0}, 1, RW_READWRITE		, DT_UINT8   , 0 , 8, 0.00000048828125f, NULL          , "s" },
 { "Phase B Cal phase delay voltage"                                 ,       "PhiB_DelayV", {0x4A, 0x0}, 1, RW_READWRITE		, DT_BIT     , 15, 0, 1.0f             , NULL          , "" },
 { "Phase C Active/reactive Energy Cal Gain"                         ,           "PQGainC", {0x4B, 0x0}, 1, RW_READWRITE		, DT_INT16   , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase C Cal phase delay"                                         ,  "PhiC_DelayCycles", {0x4C, 0x0}, 1, RW_READWRITE		, DT_UINT8   , 0 , 8, 0.00000048828125f, NULL          , "s" },
 { "Phase C Cal phase delay voltage"                                 ,       "PhiC_DelayV", {0x4C, 0x0}, 1, RW_READWRITE		, DT_BIT     , 15, 0, 1.0f             , NULL          , "" },
 { "Phase A Fundamental Active Power offset"                         ,         "PoffsetAF", {0x51, 0x0}, 1, RW_READWRITE		, DT_UINT16  , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase B Fundamental Active Power offset"                         ,         "PoffsetBF", {0x52, 0x0}, 1, RW_READWRITE		, DT_UINT16  , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase C Fundamental Active Power offset"                         ,         "PoffsetCF", {0x53, 0x0}, 1, RW_READWRITE		, DT_UINT16  , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase A Fundamental Calibration Gain"                            ,           "PGainAF", {0x51, 0x0}, 1, RW_READWRITE		, DT_UINT16  , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase B Fundamental Calibration Gain"                            ,           "PGainBF", {0x52, 0x0}, 1, RW_READWRITE		, DT_UINT16  , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase C Fundamental Calibration Gain"                            ,           "PGainCF", {0x53, 0x0}, 1, RW_READWRITE		, DT_UINT16  , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase A Voltage RMS Gain"                                        ,            "UgainA", {0x61, 0x0}, 1, RW_READWRITE		, DT_UINT16  , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase A Current RMS Gain"                                        ,            "IgainA", {0x62, 0x0}, 1, RW_READWRITE		, DT_UINT16  , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase A Voltage RMS Offset"                                      ,          "UoffsetA", {0x63, 0x0}, 1, RW_READWRITE		, DT_UINT16  , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase A Current RMS Offset"                                      ,          "IoffsetA", {0x64, 0x0}, 1, RW_READWRITE		, DT_UINT16  , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase B Voltage RMS Gain"                                        ,            "UgainB", {0x65, 0x0}, 1, RW_READWRITE		, DT_UINT16  , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase B Current RMS Gain"                                        ,            "IgainB", {0x66, 0x0}, 1, RW_READWRITE		, DT_UINT16  , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase B Voltage RMS Offset"                                      ,          "UoffsetB", {0x67, 0x0}, 1, RW_READWRITE		, DT_UINT16  , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase B Current RMS Offset"                                      ,          "IoffsetB", {0x68, 0x0}, 1, RW_READWRITE		, DT_UINT16  , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase C Voltage RMS Gain"                                        ,            "UgainC", {0x69, 0x0}, 1, RW_READWRITE		, DT_UINT16  , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase C Current RMS Gain"                                        ,            "IgainC", {0x6A, 0x0}, 1, RW_READWRITE		, DT_UINT16  , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase C Voltage RMS Offset"                                      ,          "UoffsetC", {0x6B, 0x0}, 1, RW_READWRITE		, DT_UINT16  , 0 , 0, 1.0f             , NULL          , "" },
 { "Phase C Current RMS Offset"                                      ,          "IoffsetC", {0x6C, 0x0}, 1, RW_READWRITE		, DT_UINT16  , 0 , 0, 1.0f             , NULL          , "" },
 { "Software Reset"                                                  ,         "SoftReset", {0x70, 0x0}, 1, RW_WRITE    		, DT_UINT16  , 0 , 0, 1.0f             , NULL          , "" },
 { "Energy for CF4 Forward/Reverse status"                           ,          "CF4RevST", {0x71, 0x0}, 1, RW_READ     		, DT_BIT     , 0 , 0, 1.0f             , NULL          , "" },
 { "Energy for CF3 Forward/Reverse status"                           ,          "CF3RevST", {0x71, 0x0}, 1, RW_READ     		, DT_BIT     , 1 , 0, 1.0f             , NULL          , "" },
 { "Energy for CF2 Forward/Reverse status"                           ,          "CF2RevST", {0x71, 0x0}, 1, RW_READ     		, DT_BIT     , 2 , 0, 1.0f             , NULL          , "" },
 { "Energy for CF1 Forward/Reverse status"                           ,          "CF1RevST", {0x71, 0x0}, 1, RW_READ     		, DT_BIT     , 3 , 0, 1.0f             , NULL          , "" },
 { "All phase arithmetic sum Apparent Power No load"                 ,       "TASNoloadST", {0x71, 0x0}, 1, RW_READ     		, DT_BIT     , 4 , 0, 1.0f             , NULL          , "" },
 { "All phase sum active power no-load"                              ,        "TPNoloadST", {0x71, 0x0}, 1, RW_READ     		, DT_BIT     , 5 , 0, 1.0f             , NULL          , "" },
 { "All phase sum reactive power no-load"                            ,        "TQNoloadST", {0x71, 0x0}, 1, RW_READ     		, DT_BIT     , 6 , 0, 1.0f             , NULL          , "" },
 { "Neural current OV Thresh flag"                                   ,           "INOv0ST", {0x71, 0x0}, 1, RW_READ     		, DT_BIT     , 7 , 0, 1.0f             , NULL          , "" },
 { "Current Phase Sequence Error"                                    ,          "IRevWnST", {0x71, 0x0}, 1, RW_READ     		, DT_BIT     , 8 , 0, 1.0f             , NULL          , "" },
 { "Voltage Phase Sequence Error"                                    ,          "URevWnST", {0x71, 0x0}, 1, RW_READ     		, DT_BIT     , 9 , 0, 1.0f             , NULL          , "" },
 { "Over Voltage Phase C"                                            ,        "OVPhaseAST", {0x71, 0x0}, 1, RW_READ     		, DT_BIT     , 10, 0, 1.0f             , NULL          , "" },
 { "Over Voltage Phase B"                                            ,        "OVPhaseBST", {0x71, 0x0}, 1, RW_READ     		, DT_BIT     , 11, 0, 1.0f             , NULL          , "" },
 { "Over Voltage Phase A"                                            ,        "OVPhaseCST", {0x71, 0x0}, 1, RW_READ     		, DT_BIT     , 12, 0, 1.0f             , NULL          , "" },
 { "Over Current Phase C"                                            ,        "OIPhaseAST", {0x71, 0x0}, 1, RW_READ     		, DT_BIT     , 13, 0, 1.0f             , NULL          , "" },
 { "Over Current Phase B"                                            ,        "OIPhaseBST", {0x71, 0x0}, 1, RW_READ     		, DT_BIT     , 14, 0, 1.0f             , NULL          , "" },
 { "Over Current Phase A"                                            ,        "OIPhaseCST", {0x71, 0x0}, 1, RW_READ     		, DT_BIT     , 15, 0, 1.0f             , NULL          , "" },
 { "Active Energy Register C Positive Status"                        ,         "PERegCPST", {0x72, 0x0}, 1, RW_READ     		, DT_BIT     , 0 , 0, 1.0f             , NULL          , "" },
 { "Active Energy Register B Positive Status"                        ,         "PERegBPST", {0x72, 0x0}, 1, RW_READ     		, DT_BIT     , 1 , 0, 1.0f             , NULL          , "" },
 { "Active Energy Register A Positive Status"                        ,         "PERegAPST", {0x72, 0x0}, 1, RW_READ     		, DT_BIT     , 2 , 0, 1.0f             , NULL          , "" },
 { "Active Energy Register Of ABC Positive Status"                   ,         "PERegTPST", {0x72, 0x0}, 1, RW_READ     		, DT_BIT     , 3 , 0, 1.0f             , NULL          , "" },
 { "Reactive Energy Register C Positive Status"                      ,         "QERegCPST", {0x72, 0x0}, 1, RW_READ     		, DT_BIT     , 4 , 0, 1.0f             , NULL          , "" },
 { "Reactive Energy Register B Positive Status"                      ,         "QERegBPST", {0x72, 0x0}, 1, RW_READ     		, DT_BIT     , 5 , 0, 1.0f             , NULL          , "" },
 { "Reactive Energy Register A Positive Status"                      ,         "QERegAPST", {0x72, 0x0}, 1, RW_READ     		, DT_BIT     , 6 , 0, 1.0f             , NULL          , "" },
 { "Reactive Energy Register Of ABC Positive Status"                 ,          "QERgTPST", {0x72, 0x0}, 1, RW_READ     		, DT_BIT     , 7 , 0, 1.0f             , NULL          , "" },
 { "Phase Loss C"                                                    ,      "PhaseLossCST", {0x72, 0x0}, 1, RW_READ     		, DT_BIT     , 8 , 0, 1.0f             , NULL          , "" },
 { "Phase Loss B"                                                    ,      "PhaseLossBST", {0x72, 0x0}, 1, RW_READ     		, DT_BIT     , 9 , 0, 1.0f             , NULL          , "" },
 { "Phase Loss A"                                                    ,      "PhaseLossAST", {0x72, 0x0}, 1, RW_READ     		, DT_BIT     , 10, 0, 1.0f             , NULL          , "" },
 { "Frequency Below Threshold"                                       ,          "FreqLoST", {0x72, 0x0}, 1, RW_READ     		, DT_BIT     , 11, 0, 1.0f             , NULL          , "" },
 { "Voltage Sag Phase C"                                             ,       "SagPhaseCST", {0x72, 0x0}, 1, RW_READ     		, DT_BIT     , 12, 0, 1.0f             , NULL          , "" },
 { "Voltage Sag Phase B"                                             ,       "SagPhaseBST", {0x72, 0x0}, 1, RW_READ     		, DT_BIT     , 13, 0, 1.0f             , NULL          , "" },
 { "Voltage Sag Phase A"                                             ,       "SagPhaseAST", {0x72, 0x0}, 1, RW_READ     		, DT_BIT     , 14, 0, 1.0f             , NULL          , "" },
 { "Frequency Above Threshold"                                       ,          "FreqHiST", {0x72, 0x0}, 1, RW_READ     		, DT_BIT     , 15, 0, 1.0f             , NULL          , "" },
 { "Clear Energy CF4 Status Flag"                                    ,       "CF4RevIntST", {0x73, 0x0}, 1, RW_READWRITE1CLEAR  , DT_BIT     , 0 , 0, 1.0f             , NULL          , "" },
 { "Clear Energy CF3 Status Flag"                                    ,       "CF3RevIntST", {0x73, 0x0}, 1, RW_READWRITE1CLEAR  , DT_BIT     , 1 , 0, 1.0f             , NULL          , "" },
 { "Clear Energy CF2 Status Flag"                                    ,       "CF2RevIntST", {0x73, 0x0}, 1, RW_READWRITE1CLEAR  , DT_BIT     , 2 , 0, 1.0f             , NULL          , "" },
 { "Clear Energy CF1 Status Flag"                                    ,       "CF1RevIntST", {0x73, 0x0}, 1, RW_READWRITE1CLEAR  , DT_BIT     , 3 , 0, 1.0f             , NULL          , "" },
 { "Clear all phase apparent power no-load flag"                     ,    "TASNoloadIntST", {0x73, 0x0}, 1, RW_READWRITE1CLEAR  , DT_BIT     , 4 , 0, 1.0f             , NULL          , "" },
 { "Clear all phase active power no-load flag"                       ,     "TPNoloadIntST", {0x73, 0x0}, 1, RW_READWRITE1CLEAR  , DT_BIT     , 5 , 0, 1.0f             , NULL          , "" },
 { "Clear all phase reactive power no-load flag"                     ,     "TQNoloadIntST", {0x73, 0x0}, 1, RW_READWRITE1CLEAR  , DT_BIT     , 6 , 0, 1.0f             , NULL          , "" },
 { "Clear neutral over current flag"                                 ,        "INOv0IntST", {0x73, 0x0}, 1, RW_READWRITE1CLEAR  , DT_BIT     , 7 , 0, 1.0f             , NULL          , "" },
 { "Clear current phase sequence error flag"                         ,       "IRevWnIntST", {0x73, 0x0}, 1, RW_READWRITE1CLEAR  , DT_BIT     , 8 , 0, 1.0f             , NULL          , "" },
 { "Clear voltage phase sequence error flag"                         ,       "URevWnIntST", {0x73, 0x0}, 1, RW_READWRITE1CLEAR  , DT_BIT     , 9 , 0, 1.0f             , NULL          , "" },
 { "Clear over voltage C flag"                                       ,     "OVPhaseCIntST", {0x73, 0x0}, 1, RW_READWRITE1CLEAR  , DT_BIT     , 10, 0, 1.0f             , NULL          , "" },
 { "Clear over voltage B flag"                                       ,     "OVPhaseBIntST", {0x73, 0x0}, 1, RW_READWRITE1CLEAR  , DT_BIT     , 11, 0, 1.0f             , NULL          , "" },
 { "Clear over voltage A flag"                                       ,     "OVPhaseAIntST", {0x73, 0x0}, 1, RW_READWRITE1CLEAR  , DT_BIT     , 12, 0, 1.0f             , NULL          , "" },
 { "Clear over current C flag"                                       ,     "OIPhaseCIntST", {0x73, 0x0}, 1, RW_READWRITE1CLEAR  , DT_BIT     , 13, 0, 1.0f             , NULL          , "" },
 { "Clear over current B flag"                                       ,     "OIPhaseBIntST", {0x73, 0x0}, 1, RW_READWRITE1CLEAR  , DT_BIT     , 14, 0, 1.0f             , NULL          , "" },
 { "Clear over current A flag"                                       ,     "OIPhaseAIntST", {0x73, 0x0}, 1, RW_READWRITE1CLEAR  , DT_BIT     , 15, 0, 1.0f             , NULL          , "" },
 { "Clear Active Energy Register C Positive Status"                  ,      "PERegAPIntST", {0x74, 0x0}, 1, RW_READWRITE1CLEAR  , DT_BIT     , 0 , 0, 1.0f             , NULL          , "" },
 { "Clear Active Energy Register B Positive Status"                  ,      "PERegBPIntST", {0x74, 0x0}, 1, RW_READWRITE1CLEAR  , DT_BIT     , 1 , 0, 1.0f             , NULL          , "" },
 { "Clear Active Energy Register A Positive Status"                  ,      "PERegCPIntST", {0x74, 0x0}, 1, RW_READWRITE1CLEAR  , DT_BIT     , 2 , 0, 1.0f             , NULL          , "" },
 { "Clear Active Energy Register Of ABC Positive Status"             ,      "PERegTPIntST", {0x74, 0x0}, 1, RW_READWRITE1CLEAR  , DT_BIT     , 3 , 0, 1.0f             , NULL          , "" },
 { "Clear Reactive Energy Register C Positive Status"                ,      "QERegAPIntST", {0x74, 0x0}, 1, RW_READWRITE1CLEAR  , DT_BIT     , 4 , 0, 1.0f             , NULL          , "" },
 { "Clear Reactive Energy Register B Positive Status"                ,      "QERegBPIntST", {0x74, 0x0}, 1, RW_READWRITE1CLEAR  , DT_BIT     , 5 , 0, 1.0f             , NULL          , "" },
 { "Clear Reactive Energy Register A Positive Status"                ,      "QERegCPIntST", {0x74, 0x0}, 1, RW_READWRITE1CLEAR  , DT_BIT     , 6 , 0, 1.0f             , NULL          , "" },
 { "Clear Reactive Energy Register Of ABC Positive Status"           ,       "QERgTPIntST", {0x74, 0x0}, 1, RW_READWRITE1CLEAR  , DT_BIT     , 7 , 0, 1.0f             , NULL          , "" },
 { "Clear Phase Loss C"                                              ,   "PhaseLossCIntST", {0x74, 0x0}, 1, RW_READWRITE1CLEAR  , DT_BIT     , 8 , 0, 1.0f             , NULL          , "" },
 { "Clear Phase Loss B"                                              ,   "PhaseLossBIntST", {0x74, 0x0}, 1, RW_READWRITE1CLEAR  , DT_BIT     , 9 , 0, 1.0f             , NULL          , "" },
 { "Clear Phase Loss A"                                              ,   "PhaseLossAIntST", {0x74, 0x0}, 1, RW_READWRITE1CLEAR  , DT_BIT     , 10, 0, 1.0f             , NULL          , "" },
 { "Clear Frequency Below Threshold"                                 ,       "FreqLoIntST", {0x74, 0x0}, 1, RW_READWRITE1CLEAR  , DT_BIT     , 11, 0, 1.0f             , NULL          , "" },
 { "Clear Voltage Sag Phase C"                                       ,    "SagPhaseCIntST", {0x74, 0x0}, 1, RW_READWRITE1CLEAR  , DT_BIT     , 12, 0, 1.0f             , NULL          , "" },
 { "Clear Voltage Sag Phase B"                                       ,    "SagPhaseBIntST", {0x74, 0x0}, 1, RW_READWRITE1CLEAR  , DT_BIT     , 13, 0, 1.0f             , NULL          , "" },
 { "Clear Voltage Sag Phase A"                                       ,    "SagPhaseAIntST", {0x74, 0x0}, 1, RW_READWRITE1CLEAR  , DT_BIT     , 14, 0, 1.0f             , NULL          , "" },
 { "Clear Frequency Above Threshold"                                 ,       "FreqHiIntST", {0x74, 0x0}, 1, RW_READWRITE1CLEAR  , DT_BIT     , 15, 0, 1.0f             , NULL          , "" },
 { "Enable Interrupt Energy for CF4 Forward/Reverse status"          ,       "CF4RevIntEN", {0x75, 0x0}, 1, RW_READWRITE	    , DT_BIT     , 0 , 0, 1.0f             , NULL          , "" },
 { "Enable Interrupt Energy for CF3 Forward/Reverse status"          ,       "CF3RevIntEN", {0x75, 0x0}, 1, RW_READWRITE	    , DT_BIT     , 1 , 0, 1.0f             , NULL          , "" },
 { "Enable Interrupt Energy for CF2 Forward/Reverse status"          ,       "CF2RevIntEN", {0x75, 0x0}, 1, RW_READWRITE	    , DT_BIT     , 2 , 0, 1.0f             , NULL          , "" },
 { "Enable Interrupt Energy for CF1 Forward/Reverse status"          ,       "CF1RevIntEN", {0x75, 0x0}, 1, RW_READWRITE	    , DT_BIT     , 3 , 0, 1.0f             , NULL          , "" },
 { "Enable Interrupt All phase sum Apparent Power No load"           ,    "TASNoloadIntEN", {0x75, 0x0}, 1, RW_READWRITE	    , DT_BIT     , 4 , 0, 1.0f             , NULL          , "" },
 { "Enable Interrupt All phase sum active power no-load"             ,     "TPNoloadIntEN", {0x75, 0x0}, 1, RW_READWRITE	    , DT_BIT     , 5 , 0, 1.0f             , NULL          , "" },
 { "Enable Interrupt All phase sum reactive power no-load"           ,     "TQNoloadIntEN", {0x75, 0x0}, 1, RW_READWRITE	    , DT_BIT     , 6 , 0, 1.0f             , NULL          , "" },
 { "Enable Interrupt Neural current OV Thresh flag"                  ,        "INOv0IntEN", {0x75, 0x0}, 1, RW_READWRITE	    , DT_BIT     , 7 , 0, 1.0f             , NULL          , "" },
 { "Enable Interrupt Current Phase Sequence Error"                   ,       "IRevWnIntEN", {0x75, 0x0}, 1, RW_READWRITE	    , DT_BIT     , 8 , 0, 1.0f             , NULL          , "" },
 { "Enable Interrupt Voltage Phase Sequence Error"                   ,       "URevWnIntEN", {0x75, 0x0}, 1, RW_READWRITE	    , DT_BIT     , 9 , 0, 1.0f             , NULL          , "" },
 { "Enable Interrupt Over Voltage Phase C"                           ,     "OVPhaseCIntEN", {0x75, 0x0}, 1, RW_READWRITE	    , DT_BIT     , 10, 0, 1.0f             , NULL          , "" },
 { "Enable Interrupt Over Voltage Phase B"                           ,     "OVPhaseBIntEN", {0x75, 0x0}, 1, RW_READWRITE	    , DT_BIT     , 11, 0, 1.0f             , NULL          , "" },
 { "Enable Interrupt Over Voltage Phase A"                           ,     "OVPhaseAIntEN", {0x75, 0x0}, 1, RW_READWRITE	    , DT_BIT     , 12, 0, 1.0f             , NULL          , "" },
 { "Enable Interrupt Over Current Phase C"                           ,     "OIPhaseCIntEN", {0x75, 0x0}, 1, RW_READWRITE	    , DT_BIT     , 13, 0, 1.0f             , NULL          , "" },
 { "Enable Interrupt Over Current Phase B"                           ,     "OIPhaseBIntEN", {0x75, 0x0}, 1, RW_READWRITE	    , DT_BIT     , 14, 0, 1.0f             , NULL          , "" },
 { "Enable Interrupt Over Current Phase A"                           ,     "OIPhaseAIntEN", {0x75, 0x0}, 1, RW_READWRITE	    , DT_BIT     , 15, 0, 1.0f             , NULL          , "" },
 { "Enable Interrupt Active Energy Register C Positive Status"       ,      "PERegAPIntEn", {0x76, 0x0}, 1, RW_READWRITE	    , DT_BIT     , 0 , 0, 1.0f             , NULL          , "" },
 { "Enable Interrupt Active Energy Register B Positive Status"       ,      "PERegBPIntEn", {0x76, 0x0}, 1, RW_READWRITE	    , DT_BIT     , 1 , 0, 1.0f             , NULL          , "" },
 { "Enable Interrupt Active Energy Register A Positive Status"       ,      "PERegCPIntEn", {0x76, 0x0}, 1, RW_READWRITE	    , DT_BIT     , 2 , 0, 1.0f             , NULL          , "" },
 { "Enable Interrupt Active Energy Register Of ABC Positive Status"  ,      "PERegTPIntEn", {0x76, 0x0}, 1, RW_READWRITE	    , DT_BIT     , 3 , 0, 1.0f             , NULL          , "" },
 { "Enable Interrupt Reactive Energy Register C Positive Status"     ,      "QERegAPIntEn", {0x76, 0x0}, 1, RW_READWRITE	    , DT_BIT     , 4 , 0, 1.0f             , NULL          , "" },
 { "Enable Interrupt Reactive Energy Register B Positive Status"     ,      "QERegBPIntEn", {0x76, 0x0}, 1, RW_READWRITE	    , DT_BIT     , 5 , 0, 1.0f             , NULL          , "" },
 { "Enable Interrupt Reactive Energy Register A Positive Status"     ,      "QERegCPIntEn", {0x76, 0x0}, 1, RW_READWRITE	    , DT_BIT     , 6 , 0, 1.0f             , NULL          , "" },
 { "Enable Interrupt Reactive Energy Register Of ABC Positive Status",       "QERgTPIntEn", {0x76, 0x0}, 1, RW_READWRITE	    , DT_BIT     , 7 , 0, 1.0f             , NULL          , "" },
 { "Enable Interrupt Phase Loss C"                                   ,   "PhaseLossCIntEn", {0x76, 0x0}, 1, RW_READWRITE	    , DT_BIT     , 8 , 0, 1.0f             , NULL          , "" },
 { "Enable Interrupt Phase Loss B"                                   ,   "PhaseLossBIntEn", {0x76, 0x0}, 1, RW_READWRITE	    , DT_BIT     , 9 , 0, 1.0f             , NULL          , "" },
 { "Enable Interrupt Phase Loss A"                                   ,   "PhaseLossAIntEn", {0x76, 0x0}, 1, RW_READWRITE	    , DT_BIT     , 10, 0, 1.0f             , NULL          , "" },
 { "Enable Interrupt Frequency Below Threshold"                      ,       "FreqLoIntEn", {0x76, 0x0}, 1, RW_READWRITE	    , DT_BIT     , 11, 0, 1.0f             , NULL          , "" },
 { "Enable Interrupt Voltage Sag Phase C"                            ,    "SagPhaseCIntEn", {0x76, 0x0}, 1, RW_READWRITE	    , DT_BIT     , 12, 0, 1.0f             , NULL          , "" },
 { "Enable Interrupt Voltage Sag Phase B"                            ,    "SagPhaseBIntEn", {0x76, 0x0}, 1, RW_READWRITE	    , DT_BIT     , 13, 0, 1.0f             , NULL          , "" },
 { "Enable Interrupt Voltage Sag Phase A"                            ,    "SagPhaseAIntEn", {0x76, 0x0}, 1, RW_READWRITE	    , DT_BIT     , 14, 0, 1.0f             , NULL          , "" },
 { "Enable Interrupt Frequency Above Threshold"                      ,       "FreqHiIntEn", {0x76, 0x0}, 1, RW_READWRITE	    , DT_BIT     , 15, 0, 1.0f             , NULL          , "" },
 { "Last Read/Write SPI Value"                                       ,       "LastSPIData", {0x78, 0x0}, 1, RW_READ			    , DT_UINT16  , 0 , 0, 1.0f             , NULL          , "" },
 { "Configuration Registers CRC Error"                               ,       "CFG_CRC_ERR", {0x79, 0x0}, 1, RW_READ			    , DT_BIT     , 0 , 0, 1.0f             , NULL          , "" },
 { "Internal register CRC error"                                     ,           "INT_ERR", {0x79, 0x0}, 1, RW_READ			    , DT_BIT     , 1 , 0, 1.0f             , NULL          , "" },
 { "CRC Digest"                                                      ,         "CRCDigest", {0x7A, 0x0}, 1, RW_READWRITE	    , DT_UINT16  , 0 , 0, 0.01f            , NULL          , "" },
 { "Configure Register Access Enable"                                ,       "CfgRegAccEn", {0x7F, 0x0}, 1, RW_READWRITE	    , DT_UINT16  , 0 , 0, 1.0f             , NULL          , "" },
 { "Total Forward Active Energy"                                     ,         "APenergyT", {0x80, 0x0}, 1, RW_READCLEAR	    , DT_UINT16  , 0 , 0, 0.01f            , NULL          , "" },
 { "Phase A Forward Active Energy"                                   ,         "APenergyA", {0x81, 0x0}, 1, RW_READCLEAR	    , DT_UINT16  , 0 , 0, 0.01f            , NULL          , "" },
 { "Phase B Forward Active Energy"                                   ,         "APenergyB", {0x82, 0x0}, 1, RW_READCLEAR	    , DT_UINT16  , 0 , 0, 0.01f            , NULL          , "" },
 { "Phase C Forward Active Energy"                                   ,         "APenergyC", {0x83, 0x0}, 1, RW_READCLEAR	    , DT_UINT16  , 0 , 0, 0.01f            , NULL          , "" },
 { "Total Reverse Active Energy"                                     ,         "ANenergyT", {0x84, 0x0}, 1, RW_READCLEAR	    , DT_UINT16  , 0 , 0, 0.01f            , NULL          , "" },
 { "Phase A Reverse Active Energy"                                   ,         "ANenergyA", {0x85, 0x0}, 1, RW_READCLEAR	    , DT_UINT16  , 0 , 0, 0.01f            , NULL          , "" },
 { "Phase B Reverse Active Energy"                                   ,         "ANenergyB", {0x86, 0x0}, 1, RW_READCLEAR	    , DT_UINT16  , 0 , 0, 0.01f            , NULL          , "" },
 { "Phase C Reverse Active Energy"                                   ,         "ANenergyC", {0x87, 0x0}, 1, RW_READCLEAR	    , DT_UINT16  , 0 , 0, 0.01f            , NULL          , "" },
 { "Total Forward Reactive Energy"                                   ,         "RPenergyT", {0x88, 0x0}, 1, RW_READCLEAR	    , DT_UINT16  , 0 , 0, 0.01f            , NULL          , "" },
 { "Phase A Forward Reactive Energy"                                 ,         "RPenergyA", {0x89, 0x0}, 1, RW_READCLEAR	    , DT_UINT16  , 0 , 0, 0.01f            , NULL          , "" },
 { "Phase B Forward Reactive Energy"                                 ,         "RPenergyB", {0x8A, 0x0}, 1, RW_READCLEAR	    , DT_UINT16  , 0 , 0, 0.01f            , NULL          , "" },
 { "Phase C Forward Reactive Energy"                                 ,         "RPenergyC", {0x8B, 0x0}, 1, RW_READCLEAR	    , DT_UINT16  , 0 , 0, 0.01f            , NULL          , "" },
 { "Total Reverse Reactive Energy"                                   ,         "RNenergyT", {0x8C, 0x0}, 1, RW_READCLEAR	    , DT_UINT16  , 0 , 0, 0.01f            , NULL          , "" },
 { "Phase A Reverse Reactive Energy"                                 ,         "RNenergyA", {0x8D, 0x0}, 1, RW_READCLEAR	    , DT_UINT16  , 0 , 0, 0.01f            , NULL          , "" },
 { "Phase B Reverse Reactive Energy"                                 ,         "RNenergyB", {0x8E, 0x0}, 1, RW_READCLEAR	    , DT_UINT16  , 0 , 0, 0.01f            , NULL          , "" },
 { "Phase C Reverse Reactive Energy"                                 ,         "RNenergyC", {0x8F, 0x0}, 1, RW_READCLEAR	    , DT_UINT16  , 0 , 0, 0.01f            , NULL          , "" },
 { "Total Apparent Energy"                                           ,         "SAenergyT", {0x90, 0x0}, 1, RW_READCLEAR	    , DT_UINT16  , 0 , 0, 0.01f            , NULL          , "" },
 { "Phase A Apparent Energy"                                         ,          "SenergyA", {0x91, 0x0}, 1, RW_READCLEAR	    , DT_UINT16  , 0 , 0, 0.01f            , NULL          , "" },
 { "Phase B Apparent Energy"                                         ,          "SenergyB", {0x92, 0x0}, 1, RW_READCLEAR	    , DT_UINT16  , 0 , 0, 0.01f            , NULL          , "" },
 { "Phase C Apparent Energy"                                         ,          "SenergyC", {0x93, 0x0}, 1, RW_READCLEAR	    , DT_UINT16  , 0 , 0, 0.01f            , NULL          , "" },
 { "Total Forward Active Fundamental Energy"                         ,        "APenergyTF", {0xA0, 0x0}, 1, RW_READCLEAR	    , DT_UINT16  , 0 , 0, 0.01f            , NULL          , "" },
 { "Phase A Forward Active Fundamental Energy"                       ,        "APenergyAF", {0xA1, 0x0}, 1, RW_READCLEAR	    , DT_UINT16  , 0 , 0, 0.01f            , NULL          , "" },
 { "Phase B Forward Active Fundamental Energy"                       ,        "APenergyBF", {0xA2, 0x0}, 1, RW_READCLEAR	    , DT_UINT16  , 0 , 0, 0.01f            , NULL          , "" },
 { "Phase C Forward Active Fundamental Energy"                       ,        "APenergyCF", {0xA3, 0x0}, 1, RW_READCLEAR	    , DT_UINT16  , 0 , 0, 0.01f            , NULL          , "" },
 { "Total Reverse Active Fundamental Energy"                         ,        "ANenergyTF", {0xA4, 0x0}, 1, RW_READCLEAR	    , DT_UINT16  , 0 , 0, 0.01f            , NULL          , "" },
 { "Phase A Reverse Active Fundamental Energy"                       ,        "ANenergyAF", {0xA5, 0x0}, 1, RW_READCLEAR	    , DT_UINT16  , 0 , 0, 0.01f            , NULL          , "" },
 { "Phase B Reverse Active Fundamental Energy"                       ,        "ANenergyBF", {0xA6, 0x0}, 1, RW_READCLEAR	    , DT_UINT16  , 0 , 0, 0.01f            , NULL          , "" },
 { "Phase C Reverse Active Fundamental Energy"                       ,        "ANenergyCF", {0xA7, 0x0}, 1, RW_READCLEAR	    , DT_UINT16  , 0 , 0, 0.01f            , NULL          , "" },
 { "Total Forward Active Harmonic Energy"                            ,        "RPenergyTH", {0xA8, 0x0}, 1, RW_READCLEAR	    , DT_UINT16  , 0 , 0, 0.01f            , NULL          , "" },
 { "Phase A Forward Active Harmonic Energy"                          ,        "RPenergyAH", {0xA9, 0x0}, 1, RW_READCLEAR	    , DT_UINT16  , 0 , 0, 0.01f            , NULL          , "" },
 { "Phase B Forward Active Harmonic Energy"                          ,        "RPenergyBH", {0xAA, 0x0}, 1, RW_READCLEAR	    , DT_UINT16  , 0 , 0, 0.01f            , NULL          , "" },
 { "Phase C Forward Active Harmonic Energy"                          ,        "RPenergyCH", {0xAB, 0x0}, 1, RW_READCLEAR	    , DT_UINT16  , 0 , 0, 0.01f            , NULL          , "" },
 { "Total Reverse Active Harmonic Energy"                            ,        "RNenergyTH", {0xAC, 0x0}, 1, RW_READCLEAR	    , DT_UINT16  , 0 , 0, 0.01f            , NULL          , "" },
 { "Phase A Reverse Active Harmonic Energy"                          ,        "RNenergyAH", {0xAD, 0x0}, 1, RW_READCLEAR	    , DT_UINT16  , 0 , 0, 0.01f            , NULL          , "" },
 { "Phase B Reverse Active Harmonic Energy"                          ,        "RNenergyBH", {0xAE, 0x0}, 1, RW_READCLEAR	    , DT_UINT16  , 0 , 0, 0.01f            , NULL          , "" },
 { "Phase C Reverse Active Harmonic Energy"                          ,        "RNenergyCH", {0xAF, 0x0}, 1, RW_READCLEAR	    , DT_UINT16  , 0 , 0, 0.01f            , NULL          , "" },
 { "All Phase Total Active Power"                                    ,            "PmeanT", {0xB0,0xC0}, 2, RW_READ			    , DT_INT32   , 0 , 0, 0.00032f         , NULL          , "" },
 { "Phase A Active Power"                                            ,            "PmeanA", {0xB1,0xC1}, 2, RW_READ			    , DT_INT32   , 0 , 0, 0.00032f         , NULL          , "W" },
 { "Phase B Active Power"                                            ,            "PmeanB", {0xB2,0xC2}, 2, RW_READ			    , DT_INT32   , 0 , 0, 0.00032f         , NULL          , "W" },
 { "Phase C Active Power"                                            ,            "PmeanC", {0xB3,0xC3}, 2, RW_READ			    , DT_INT32   , 0 , 0, 0.00032f         , NULL          , "W" },
 { "All Phase Total Reactive Power"                                  ,            "QmeanT", {0xB4,0xC4}, 2, RW_READ			    , DT_INT32   , 0 , 0, 0.00032f         , NULL          , "var" },
 { "Phase A Reactive Power"                                          ,            "QmeanA", {0xB5,0xC5}, 2, RW_READ			    , DT_INT32   , 0 , 0, 0.00032f         , NULL          , "var" },
 { "Phase B Reactive Power"                                          ,            "QmeanB", {0xB6,0xC6}, 2, RW_READ			    , DT_INT32   , 0 , 0, 0.00032f         , NULL          , "var" },
 { "Phase C Reactive Power"                                          ,            "QmeanC", {0xB7,0xC7}, 2, RW_READ			    , DT_INT32   , 0 , 0, 0.00032f         , NULL          , "var" },
 { "All Phase Total Apparent Power"                                  ,            "SmeanT", {0xB8,0xC8}, 2, RW_READ			    , DT_INT32   , 0 , 0, 0.00032f         , NULL          , "VA" },
 { "Phase A Apparent Power"                                          ,            "SmeanA", {0xB9,0xC9}, 2, RW_READ			    , DT_INT32   , 0 , 0, 0.00032f         , NULL          , "VA" },
 { "Phase B Apparent Power"                                          ,            "SmeanB", {0xBA,0xCA}, 2, RW_READ			    , DT_INT32   , 0 , 0, 0.00032f         , NULL          , "VA" },
 { "Phase C Apparent Power"                                          ,            "SmeanC", {0xBB,0xCB}, 2, RW_READ			    , DT_INT32   , 0 , 0, 0.00032f         , NULL          , "VA" },
 { "All Phase Power Factor"                                          ,           "PFmeanT", {0xBC, 0x0}, 1, RW_READ			    , DT_UINT16  , 0 , 0, 0.001f           , NULL          , " " },
 { "Phase A Power Factor"                                            ,           "PFmeanA", {0xBD, 0x0}, 1, RW_READ			    , DT_UINT16  , 0 , 0, 0.001f           , NULL          , " " },
 { "Phase B Power Factor"                                            ,           "PFmeanB", {0xBE, 0x0}, 1, RW_READ			    , DT_UINT16  , 0 , 0, 0.001f           , NULL          , " " },
 { "Phase C Power Factor"                                            ,           "PFmeanC", {0xBF, 0x0}, 1, RW_READ			    , DT_UINT16  , 0 , 0, 0.001f           , NULL          , " " },
 { "All Phase Total Active Fundamental Power"                        ,           "PmeanTF", {0xD0,0xE0}, 2, RW_READ			    , DT_INT32   , 0 , 0, 0.00032f         , NULL          , "W" },
 { "Phase A Active Fundamental Power"                                ,           "PmeanAF", {0xD1,0xE1}, 2, RW_READ			    , DT_INT32   , 0 , 0, 0.00032f         , NULL          , "W" },
 { "Phase B Active Fundamental Power"                                ,           "PmeanBF", {0xD2,0xE2}, 2, RW_READ			    , DT_INT32   , 0 , 0, 0.00032f         , NULL          , "W" },
 { "Phase C Active Fundamental Power"                                ,           "PmeanCF", {0xD3,0xE3}, 2, RW_READ			    , DT_INT32   , 0 , 0, 0.00032f         , NULL          , "W" },
 { "All Phase Total Harmonic Power"                                  ,           "PmeanTH", {0xD0,0xE0}, 2, RW_READ			    , DT_INT32   , 0 , 0, 0.00032f         , NULL          , "W" },
 { "Phase A Harmonic Power"                                          ,           "PmeanAH", {0xD1,0xE1}, 2, RW_READ			    , DT_INT32   , 0 , 0, 0.00032f         , NULL          , "W" },
 { "Phase B Harmonic Power"                                          ,           "PmeanBH", {0xD2,0xE2}, 2, RW_READ			    , DT_INT32   , 0 , 0, 0.00032f         , NULL          , "W" },
 { "Phase C Harmonic Power"                                          ,           "PmeanCH", {0xD3,0xE3}, 2, RW_READ			    , DT_INT32   , 0 , 0, 0.00032f         , NULL          , "W" },
 { "Phase A Voltage RMS"                                             ,             "UrmsA", {0xD9, 0x0}, 1, RW_READ			    , DT_INT16   , 0 , 0, 0.01f            , NULL          , "V" },
 { "Phase B Voltage RMS"                                             ,             "UrmsB", {0xDA, 0x0}, 1, RW_READ			    , DT_INT16   , 0 , 0, 0.01f            , NULL          , "V" },
 { "Phase C Voltage RMS"                                             ,             "UrmsC", {0xDB, 0x0}, 1, RW_READ			    , DT_INT16   , 0 , 0, 0.01f            , NULL          , "V" },
 { "N Current RMS"                                                   ,             "IrmsN", {0xDC, 0x0}, 1, RW_READ			    , DT_INT16   , 0 , 0, 0.001f           , NULL          , "A" },
 { "A Current RMS"                                                   ,             "IrmsA", {0xDD, 0x0}, 1, RW_READ			    , DT_INT16   , 0 , 0, 0.001f           , NULL          , "A" },
 { "B Current RMS"                                                   ,             "IrmsB", {0xDE, 0x0}, 1, RW_READ			    , DT_INT16   , 0 , 0, 0.001f           , NULL          , "A" },
 { "C Current RMS"                                                   ,             "IrmsC", {0xDF, 0x0}, 1, RW_READ			    , DT_INT16   , 0 , 0, 0.001f           , NULL          , "A" },
 { "A Peak Voltage"                                                  ,            "UPeakA", {0xF1, 0x0}, 1, RW_READ			    , DT_INT16   , 0 , 0, 1.0f             , calculatePeakV, "V" },
 { "B Peak Voltage"                                                  ,            "UPeakB", {0xF2, 0x0}, 1, RW_READ			    , DT_INT16   , 0 , 0, 1.0f             , calculatePeakV, "V" },
 { "C Peak Voltage"                                                  ,            "UPeakC", {0xF3, 0x0}, 1, RW_READ			    , DT_INT16   , 0 , 0, 1.0f             , calculatePeakV, "V" },
 { "A Peak Current"                                                  ,            "UPeakA", {0xF5, 0x0}, 1, RW_READ			    , DT_INT16   , 0 , 0, 1.0f             , calculatePeakI, "A" },
 { "B Peak Current"                                                  ,            "UPeakB", {0xF6, 0x0}, 1, RW_READ			    , DT_INT16   , 0 , 0, 1.0f             , calculatePeakI, "A" },
 { "C Peak Current"                                                  ,            "UPeakC", {0xF7, 0x0}, 1, RW_READ			    , DT_INT16   , 0 , 0, 1.0f             , calculatePeakI, "A" },
 { "Frequency"                                                       ,              "Freq", {0xF8, 0x0}, 1, RW_READ			    , DT_INT16   , 0 , 0, 0.01f            , NULL          , "Hz" },
 { "A mean phase angle"                                              ,           "PAngleA", {0xF9, 0x0}, 1, RW_READ			    , DT_INT16   , 0 , 0, 0.1f             , NULL          , "°" },
 { "B mean phase angle"                                              ,           "PAngleB", {0xFA, 0x0}, 1, RW_READ			    , DT_INT16   , 0 , 0, 0.1f             , NULL          , "°" },
 { "C mean phase angle"                                              ,           "PAngleC", {0xFB, 0x0}, 1, RW_READ			    , DT_INT16   , 0 , 0, 0.1f             , NULL          , "°" },
 { "IC Temperature"                                                  ,              "Temp", {0xFC, 0x0}, 1, RW_READ			    , DT_INT16   , 0 , 0, 1.0f             , NULL          , "°C" },
 { "Phase A Voltage Phase Angle"                                     ,           "UangleA", {0xFD, 0x0}, 1, RW_READ			    , DT_INT16   , 0 , 0, 0.1f             , NULL          , "°" },
 { "Phase B Voltage Phase Angle"                                     ,           "UangleB", {0xFE, 0x0}, 1, RW_READ			    , DT_INT16   , 0 , 0, 0.1f             , NULL          , "°" },
 { "Phase C Voltage Phase Angle"                                     ,           "UangleC", {0xFF, 0x0}, 1, RW_READ			    , DT_INT16   , 0 , 0, 0.1f             , NULL          , "°" },
};

const uint16_t registerCount = sizeof(registers) / sizeof(registers[0]);